// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Remoment7Inch

#ifndef _REMOMENT7INCH_UI_H
#define _REMOMENT7INCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Startup.h"
#include "ui_Now_Playing.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * MoveIn_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1778644822);   // assets/ChatGPT Image 12 feb 2026, 10_08_42.png
LV_IMG_DECLARE( ui_img_album_wallpaper_png);   // assets/album_wallpaper.png
LV_IMG_DECLARE( ui_img_505234510);   // assets/La_Roux_(album).png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
