// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Remoment7Inch

#include "ui.h"

lv_obj_t *uic_playing_progress;
lv_obj_t *uic_song_length;
lv_obj_t *uic_progress;
lv_obj_t *uic_Artist;
lv_obj_t *uic_track_name;
lv_obj_t *uic_album_art;
lv_obj_t *uic_Now_Playing;
lv_obj_t *ui_Now_Playing = NULL;lv_obj_t *ui_album_art = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_track_name = NULL;lv_obj_t *ui_Artist = NULL;lv_obj_t *ui_Player = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_progress = NULL;lv_obj_t *ui_song_length = NULL;lv_obj_t *ui_playing_progress = NULL;lv_obj_t *ui_Volume_Indicator = NULL;
// event funtions
void ui_event_Now_Playing( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP  ) {
lv_indev_wait_release(lv_indev_get_act());
      MoveIn_Animation(ui_Volume_Indicator, 0);
}
}

// build funtions

void ui_Now_Playing_screen_init(void)
{
ui_Now_Playing = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Now_Playing, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Now_Playing, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Now_Playing, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Now_Playing, &ui_img_album_wallpaper_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_album_art = lv_img_create(ui_Now_Playing);
lv_img_set_src(ui_album_art, &ui_img_505234510);
lv_obj_set_width( ui_album_art, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_album_art, LV_SIZE_CONTENT);   /// 320
lv_obj_set_x( ui_album_art, -283 );
lv_obj_set_y( ui_album_art, -100 );
lv_obj_set_align( ui_album_art, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_album_art, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_album_art, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container2 = lv_obj_create(ui_Now_Playing);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 400);
lv_obj_set_height( ui_Container2, 58);
lv_obj_set_x( ui_Container2, 99 );
lv_obj_set_y( ui_Container2, -202 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_track_name = lv_label_create(ui_Container2);
lv_obj_set_width( ui_track_name, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_track_name, LV_SIZE_CONTENT);   /// 200
lv_obj_set_x( ui_track_name, -6 );
lv_obj_set_y( ui_track_name, -219 );
lv_obj_set_align( ui_track_name, LV_ALIGN_CENTER );
lv_label_set_text(ui_track_name,"In For the Kill");
lv_obj_set_style_text_font(ui_track_name, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Artist = lv_label_create(ui_Container2);
lv_obj_set_width( ui_Artist, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Artist, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Artist, -4 );
lv_obj_set_y( ui_Artist, -99 );
lv_obj_set_align( ui_Artist, LV_ALIGN_CENTER );
lv_label_set_text(ui_Artist,"La Roux");
lv_obj_set_style_text_color(ui_Artist, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Artist, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Artist, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Player = lv_label_create(ui_Now_Playing);
lv_obj_set_width( ui_Player, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Player, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Player, -10 );
lv_obj_set_y( ui_Player, -2 );
lv_obj_set_align( ui_Player, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_Player,"Beoplay M5");

ui_Container1 = lv_obj_create(ui_Now_Playing);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_height( ui_Container1, 50);
lv_obj_set_width( ui_Container1, lv_pct(80));
lv_obj_set_x( ui_Container1, 1 );
lv_obj_set_y( ui_Container1, 185 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_progress = lv_label_create(ui_Container1);
lv_obj_set_width( ui_progress, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_progress, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_progress, -400 );
lv_obj_set_y( ui_progress, 140 );
lv_label_set_text(ui_progress,"1:50");

ui_song_length = lv_label_create(ui_Container1);
lv_obj_set_width( ui_song_length, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_song_length, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_song_length, 395 );
lv_obj_set_y( ui_song_length, 124 );
lv_obj_set_align( ui_song_length, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_song_length,"3:08");
lv_obj_set_style_pad_left(ui_song_length, 760, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_song_length, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_song_length, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_song_length, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_playing_progress = lv_slider_create(ui_Container1);
lv_slider_set_value( ui_playing_progress, 48, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_playing_progress)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_playing_progress, 0, LV_ANIM_OFF);
lv_obj_set_height( ui_playing_progress, 10);
lv_obj_set_width( ui_playing_progress, lv_pct(100));
lv_obj_set_x( ui_playing_progress, 15 );
lv_obj_set_y( ui_playing_progress, 181 );
lv_obj_set_align( ui_playing_progress, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_playing_progress, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_playing_progress, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_playing_progress, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_playing_progress, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_playing_progress, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_playing_progress, lv_color_hex(0x521010), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_playing_progress, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_playing_progress, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_playing_progress, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_playing_progress, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_playing_progress, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_playing_progress, 3, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Volume_Indicator = lv_obj_create(ui_Now_Playing);
lv_obj_set_width( ui_Volume_Indicator, lv_pct(100));
lv_obj_set_height( ui_Volume_Indicator, lv_pct(20));
lv_obj_set_x( ui_Volume_Indicator, 2 );
lv_obj_set_y( ui_Volume_Indicator, 119 );
lv_obj_set_align( ui_Volume_Indicator, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_Volume_Indicator, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Now_Playing, ui_event_Now_Playing, LV_EVENT_ALL, NULL);
uic_Now_Playing = ui_Now_Playing;
uic_album_art = ui_album_art;
uic_track_name = ui_track_name;
uic_Artist = ui_Artist;
uic_progress = ui_progress;
uic_song_length = ui_song_length;
uic_playing_progress = ui_playing_progress;

}

void ui_Now_Playing_screen_destroy(void)
{
   if (ui_Now_Playing) lv_obj_del(ui_Now_Playing);

// NULL screen variables
uic_Now_Playing= NULL;
ui_Now_Playing= NULL;
uic_album_art= NULL;
ui_album_art= NULL;
ui_Container2= NULL;
uic_track_name= NULL;
ui_track_name= NULL;
uic_Artist= NULL;
ui_Artist= NULL;
ui_Player= NULL;
ui_Container1= NULL;
uic_progress= NULL;
ui_progress= NULL;
uic_song_length= NULL;
ui_song_length= NULL;
uic_playing_progress= NULL;
ui_playing_progress= NULL;
ui_Volume_Indicator= NULL;

}
