// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Remoment7Inch

#ifndef UI_NOW_PLAYING_H
#define UI_NOW_PLAYING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Now_Playing
extern void ui_Now_Playing_screen_init(void);
extern void ui_Now_Playing_screen_destroy(void);
extern void ui_event_Now_Playing( lv_event_t * e);
extern lv_obj_t *ui_Now_Playing;
extern lv_obj_t *ui_album_art;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_track_name;
extern lv_obj_t *ui_Artist;
extern lv_obj_t *ui_Player;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_progress;
extern lv_obj_t *ui_song_length;
extern lv_obj_t *ui_playing_progress;
extern lv_obj_t *ui_Volume_Indicator;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Now_Playing;
extern lv_obj_t *uic_album_art;
extern lv_obj_t *uic_track_name;
extern lv_obj_t *uic_Artist;
extern lv_obj_t *uic_progress;
extern lv_obj_t *uic_song_length;
extern lv_obj_t *uic_playing_progress;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

