// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Remoment7Inch

#include "ui.h"

lv_obj_t *uic_Startup;
lv_obj_t *ui_Startup = NULL;
// event funtions
void ui_event_Startup( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_Now_Playing, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Now_Playing_screen_init);
}
}

// build funtions

void ui_Startup_screen_init(void)
{
ui_Startup = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Startup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Startup, &ui_img_1778644822, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_tiled(ui_Startup, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Startup, ui_event_Startup, LV_EVENT_ALL, NULL);
uic_Startup = ui_Startup;

}

void ui_Startup_screen_destroy(void)
{
   if (ui_Startup) lv_obj_del(ui_Startup);

// NULL screen variables
uic_Startup= NULL;
ui_Startup= NULL;

}
