// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Remoment7Inch

#ifndef UI_STARTUP_H
#define UI_STARTUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Startup
extern void ui_Startup_screen_init(void);
extern void ui_Startup_screen_destroy(void);
extern void ui_event_Startup( lv_event_t * e);
extern lv_obj_t *ui_Startup;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Startup;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

